services:
  - type: web
    name: agriroute-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn agriroute.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
