# Generated by Django 5.2.1 on 2025-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_transportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('gps', models.CharField(blank=True, max_length=100)),
                ('farm_size', models.CharField(blank=True, max_length=50)),
                ('crops', models.TextField(blank=True)),
                ('planting_dates', models.TextField(blank=True)),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('ph_level', models.CharField(blank=True, max_length=50)),
                ('irrigation_type', models.CharField(blank=True, max_length=50)),
                ('water_source', models.CharField(blank=True, max_length=100)),
                ('input_costs', models.TextField(blank=True)),
                ('selling_prices', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=200)),
                ('load_capacity', models.PositiveIntegerField()),
                ('fuel_efficiency', models.FloatField()),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
